### ISSUE TITLE
Swift 4.0.3 compilation errors

### ISSUE THREAD

**Issue by alexandru-crossover** [danielgindi/ChartsRealm#18]
Hi,

The latest version, 3.0.4, does not compile when using Swift 4.0.3. I see that the compilation errors have already been fixed [here](https://github.com/danielgindi/ChartsRealm/commit/d7062d1fed6e876b1e46572481646d2952ca99ca), but they have not been released yet. Are there any plans for a 3.0.5 version that will include those fixes?

**Comment by jjatie** [comment]
@liuxuan30 I know you're busy, but would you have time to make sure it runs fine to release with Charts 3.1? If not, I will take care of it immediately after we release Charts 3.1 (first week of February)

**Comment by liuxuan30** [comment]
It does compile with swift 4.0.3, if you build yourself, or from carthage, but it does not work with pod.
Be sure to include more information like which way you use.

The sole problem is that, Realm 3.1.0 saying its prebuilt framework supports 4.0.3, while it's not. So you have to use source code to build:
```
*** Downloading realm-cocoa.framework binary at "v3.1.0"
*** Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out realm-cocoa at "v3.1.0"
```

**Comment by liuxuan30** [comment]
Current carthage file use master branch to build from scratch, which takes a long time. So it's up to you. 

You can learn when prebuilt 4.0.3 framework came out here: https://github.com/realm/realm-cocoa/issues/5538

BTW, @alexandru-crossover are you using Realm or RealmSwift? I don't think RealmSwift works fine with ChartRealm, from my PR: #17

**Comment by alexandru-crossover** [comment]
@liuxuan30 We are using CocoaPods and RealmSwift. We did not encounter any issues related to RealmSwift so far.

I'm not sure how RealmSwift is involved here. That compiles successfully right now. Are you saying that we first need a new version of RealmSwift and only then we'll have a new version of ChartsRealm?

**Comment by liuxuan30** [comment]
OK so two things:
1. How do you query your data and pass it to ChartRealm, in RealmSwift or Realm? I don't think current implementation supports RealmSwift. I'm interested how you uses ChartsRealm in your app.
2. "That compiles successfully right now" can you explain?

**Comment by alexandru-crossover** [comment]
@liuxuan30 
1. I'll get back to you on this. I need to check the code deeper.
2. I mean that `xcodebuild` throws the following errors for ChartsRealm:
```
[16:49:25][Step 2/3] [08:49:25]: ▸ Compiling RealmBarDataSet.swift
[16:49:25][Step 2/3] [08:49:25]: ▸ ❌  /Volumes/ExtraDisk/TeamCity/buildAgent/work/ec8b670df1327810/Pods/ChartsRealm/ChartsRealm/Classes/Data/RealmBarDataSet.swift:204:29: cannot use mutating member on immutable value: 'iterator' is a 'let' constant
[16:49:25][Step 2/3] [08:49:25]: ▸ while let val = iterator.next()
[16:49:25][Step 2/3] [08:49:25]: ▸                             ^~~~~~~~
[16:49:25][Step 2/3] [08:49:25]: ▸ Compiling RealmBarLineScatterCandleBubbleDataSet.swift
[16:49:25][Step 2/3] [08:49:25]: ▸ Compiling RealmBaseDataSet.swift
[16:49:25][Step 2/3] [08:49:25]: ▸ ❌  /Volumes/ExtraDisk/TeamCity/buildAgent/work/ec8b670df1327810/Pods/ChartsRealm/ChartsRealm/Classes/Data/RealmBaseDataSet.swift:242:23: cannot use mutating member on immutable value: 'iterator' is a 'let' constant
[16:49:25][Step 2/3] [08:49:25]: ▸ while let e = iterator.next()
```

There are no such errors for RealmSwift.

**Comment by liuxuan30** [comment]
ok, thanks.
for .1, please just let me know how you fetch the data, and pass them to ChartsRealm. I need code level details, but you can hide your information.
for .2, `let e = iterator.next()` works fine on my side, with master branch and realm-cocoa master branch, on Swift 4.0.3

**Comment by alexandru-crossover** [comment]
@liuxuan30 Yes, that works on the master branch, which was fixed [here](https://github.com/danielgindi/ChartsRealm/commit/d7062d1fed6e876b1e46572481646d2952ca99ca), but not with the latest CocoaPods version, 3.0.4, which does not contain that fix.

For now, as a workaround, we reverted to 3.0.3, which compiles successfully on Swift 4.0.3

**Comment by liuxuan30** [comment]
I see so you use pod here. I tried to push to pod, however always compile issues, while carthage works fine.

I'm no pod expert, you can try make a PR to fix it and I could merge. Or wait Realm release a prebuilt framework for 4.0.3, and I can try with pod again.

**Comment by liuxuan30** [comment]
pod has been bumped to 3.0.5 with latest Xcode fashion.
